### ISSUE TITLE
exceptions testing any binary

### ISSUE THREAD

**Issue by roninteger** [montyly/gueb#6]
Hello Montyly, 

I've been testing gueb using your public VM and installed everything on a new one. Seems to work everything, IDA 6.9 with Binnavi 6.1 (latest) and binexport 6 (latest). Using your example seems to be working fine, but gui.py fails with any binary. For example /bin/echo, from ubuntu 32-bit build. 

Unknown mnemonic: ud2
Unknown mnemonic: ud2
sub_10F63
Exception in thread "AWT-EventQueue-0"  at com.google.security.zynamics.binnavi.API.disassembly.Function.getReilCode(Function.java:337)
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.google.security.zynamics.binnavi.API.reil.InternalTranslationException: com.google.security.zynamics.reil.translators.InternalTranslationException: Error: The operands of SBB instructions must have equal size

I don't know if you're familiar with this exception.  I'm using Binnavi 6.1 release binnavi-all.jar. 

Thank you

**Comment by montyly** [comment]
Hi,
Thanks for your interest in GUEB.

Could you try with the last github version of binnavi?
Also, did you try with a simple (and small) "hello world" example?

I just tried on my machine (IDA 6.8, last github version of binnavi), /bin/echo from an Ubuntu 32 bits is working.

Notice that the version of GUEB in the public VM is quite old, I would recommend to do a " _cd /home/gueb/Desktop/gueb && git pull && cd src && make_" 

Best,
